name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        directory:
          - "2022/day-01"
          - "2022/day-02"
          - "2022/day-03"
          - "2022/day-04"
          - "2022/day-05"
          - "2022/day-06"
          - "2022/day-07"
          - "2022/day-08"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test -r
        working-directory: "${{ matrix.directory }}"
